### PR TITLE
Add example terraform

### PR DESCRIPTION
**Pull request by keirlawson**

### CODE REVIEW

**Review by d-fernandes — COMMENTED** [review]
Not sure I understand this PR @keirlawson. Is it the idea that whoever uses the DeDuplication library would now have an example of which Terraform they need to run in order to have the resources that this lib requires ?

**Comment by keirlawson** [comment]
Yep that's the idea

**Comment by rcdmrl** [comment]
> Not sure I understand this PR @keirlawson. Is it the idea that whoever uses the DeDuplication library would now have an example of which Terraform they need to run in order to have the resources that this lib requires ?

Yeah, seems like it indeed @d-fernandes. Like a way to document how would the DynamoDB table table look like (PK and SK) without having to read Scala.

**Review by rcdmrl — APPROVED** [review]
I personally like the idea but let's wait for other @ovotech/comms reviews :)

**Review by d-fernandes — APPROVED** [review]

**Pull request merged**
